// <auto-generated />
namespace SWOP.Transport.DbRepositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddRowVersionToVehicle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRowVersionToVehicle));
        
        string IMigrationMetadata.Id
        {
            get { return "201908230925540_AddRowVersionToVehicle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
